
// This file is automatically generated. Do not edit it directly.
import React, { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { NetworkSnapshot, networkService } from "@/services/networkService";
import { ChartContainer, LineChart } from "@/components/ui/chart";
import { BarChart4, ChartLineIcon } from "lucide-react";

interface NetworkChartProps {
  selectedNetwork?: string;
  sharedMetrics?: NetworkSnapshot[];
}

const NetworkChart: React.FC<NetworkChartProps> = ({ 
  selectedNetwork,
  sharedMetrics 
}) => {
  const [data, setData] = useState<NetworkSnapshot[]>([]);
  const [chartType, setChartType] = useState<"ping" | "speed">("ping");
  
  useEffect(() => {
    if (sharedMetrics) {
      setData(sharedMetrics);
      return;
    }
    
    const unsubscribe = networkService.subscribe((newData) => {
      setData(newData);
    }, selectedNetwork);
    
    return () => {
      unsubscribe();
    };
  }, [selectedNetwork, sharedMetrics]);

  // Format time labels on x-axis
  const formatTimeLabel = (timestamp: number) => {
    const date = new Date(timestamp);
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });
  };

  const getPingData = () => {
    return data.map((item) => ({
      name: formatTimeLabel(item.timestamp),
      ping: item.pingTime < 0 ? null : item.pingTime,
      timestamp: item.timestamp,
    }));
  };
  
  const getSpeedData = () => {
    return data.map((item) => ({
      name: formatTimeLabel(item.timestamp),
      download: item.downloadSpeed,
      upload: item.uploadSpeed,
      timestamp: item.timestamp,
    }));
  };
  
  const chartData = chartType === "ping" ? getPingData() : getSpeedData();

  return (
    <Card>
      <CardHeader className="pb-2">
        <div className="flex justify-between items-center">
          <CardTitle className="flex items-center gap-2">
            <ChartLineIcon className="h-4 w-4" />
            {chartType === "ping" ? "Ping Latency" : "Network Speed"}
          </CardTitle>
          
          <div className="flex gap-2">
            <Select
              value={chartType}
              onValueChange={(value) => setChartType(value as "ping" | "speed")}
            >
              <SelectTrigger className="w-[140px]">
                <SelectValue placeholder="Chart Type" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="ping">Ping Latency</SelectItem>
                <SelectItem value="speed">Speed Test</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <div className="h-[300px]">
          {chartType === "ping" ? (
            <ChartContainer>
              <LineChart
                data={chartData}
                index="timestamp"
                categories={["ping"]}
                colors={["blue"]}
                valueFormatter={(value) => `${value}ms`}
                yAxisWidth={50}
                showAnimation={true}
                showLegend={false}
                showGridLines={true}
                showTooltip={true}
                startEndOnly={chartData.length > 30}
                className="h-[300px]"
              />
            </ChartContainer>
          ) : (
            <ChartContainer>
              <LineChart
                data={chartData}
                index="timestamp"
                categories={["download", "upload"]}
                colors={["green", "blue"]}
                valueFormatter={(value) => `${value?.toFixed(2)} Mbps`}
                yAxisWidth={70}
                showAnimation={true}
                showLegend={true}
                showGridLines={true}
                showTooltip={true}
                startEndOnly={chartData.length > 30}
                className="h-[300px]"
              />
            </ChartContainer>
          )}
        </div>
        
        <div className="text-xs text-muted-foreground mt-4">
          {data.length === 0 ? (
            "No data available. Start monitoring to see results."
          ) : (
            `Showing ${data.length} data points from ${formatTimeLabel(data[0]?.timestamp)} to ${formatTimeLabel(data[data.length - 1]?.timestamp)}`
          )}
        </div>
      </CardContent>
    </Card>
  );
};

export default NetworkChart;
